version: '3'
services:
  node:
    container_name: test
    image: node:18.15.0-alpine
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      NODE_ENV: development
    ports:
      - 5174:5173
    command: >
            sh -c "npm install && npm run dev"
    restart: always